import { Geist_Mono,Poppins } from "next/font/google";
import "./globals.css";




export const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fontPoppins = Poppins({
  variable : '--font-pop',
  subsets : ['latin'],
  weight : ['400','600']
}) 

export const metadata = {
  title: "News portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`h-full antialiased`}
    >
      <body className={`${fontPoppins} min-h-full flex flex-col`}>
        {children}
        </body>
    </html>
  );
}
